name: Claude Action

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude_action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          # This is a placeholder, please replace it with your Anthropic API key
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            Please review the changes in this pull request.
            Focus on:
            - Code quality and readability
            - Potential bugs or edge cases
            - Adherence to best practices
            - Suggestions for improvement
